version: "3"

services:
  lokalnygospodarz:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  notificationservice:
    build: ./Library.NotificationService2/
    ports:
      - 92:80
    depends_on:
      - lokalnygospodarz

  librarywebapi:
    build: ./Library.WebApi/
    ports:
      - 91:80
    depends_on:
      - notificationservice

  libraryweb:
    build: ./Library.Web/
    ports:
      - 90:80
    depends_on:
      - librarywebapi